name: Build Game

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Haxe
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.3.6
