name: Build Game

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Haxe
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.3.6

    - name: Install Haxelibs
      run: |
        haxelib install lime 8.2.2
        haxelib install openfl 9.4.1
        haxelib install flixel 6.0.0
        haxelib install flixel-addons 3.3.2
        haxelib install flixel-tools 1.5.1
        haxelib install hxcpp-debug-server 1.2.4
        haxelib install hxdiscord_rpc 1.3.0
        haxelib run lime setup -y
        haxelib run openfl setup -y
        haxelib run flixel-tools setup -y

    - name: Test Build (HTML5)
      run: lime test html5 --no-launch
